name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install homeassistant pytest pytest-asyncio pytest-cov pytest-timeout aiohttp
      - name: Run tests
        run: |
          pytest tests/ -q --timeout=60
